APP_NAME: SCnorm_v0.99.2
EXPRESSION_FILE_NAME: expression_data.tsv
CELL_META_FILE_NAME: cell_metadata.tsv
MANIFEST_FILE_NAME: manifest.yml
PROPTOUSE: 0.25
TAU: 0.5
REPORTSF: FALSE
FILTERCELLNUM: 10
K: NULL
FILTEREXPRESSION: 0
THRESH: 0.1
DITHERCOUNTS: FALSE
WITHINSAMPLE: NULL
USESPIKES: FALSE
